# Generated by Django 3.2.4 on 2021-06-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_id', models.CharField(max_length=16)),
                ('icon', models.CharField(max_length=256, null=True)),
                ('rating', models.CharField(max_length=4, null=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
